### ISSUE TITLE
Additional functionality

### ISSUE THREAD

**Issue by milanborchert** [Intron7/alpha_viewer#1]
Hello. thank you for writing this very helpful visualization class for alphafold. The included features work as described for me. However I was wondering, if you could potentially include some further options:
1. select different models: Alphafold gives multiple results which are ranked upon creation. As I understand it, your tool only uses the highest ranked model, which makes sense. However an option to als display the other results would be nice.
2. only display part of protein: for your multimer coloring you already have the function to only select parts of the rendered model and assign different colors. Another optional flag that lets one specify only a region of the protein to be shown would be nice for better viewability
3. export question: in what way would you export the resulting images? Is it possible to export the movable protein cartoon and reopen it later or would you suggest using a new notebook for every protein I want to visualize?

**Comment by Intron7** [comment]
Hey Milan,
Thanks for the kind words. 
1. This should be easy to implement. I would set an optional argument when creating the object, that would choose the "best" model if its None.
2. Yeah I think that should work. I have some ideas how to Implement this.
3. I would love to give the Option to create a JPEG or PDF of the current view. However to the best of my knowledge it's currently not possible with py3Dmol. The best option is to create a screenshot of the view. It's not nice I know. If you know a better library than py3Dmol that enables this function, I would like to switch to it for visualisation. 

I'll try to write the updated code on the weekend and create a new version.
Yours Severin

**Comment by aspitaleri** [comment]
Nice tool indeed! I am using it and it works fine on MacOSX M1. Additional feature would be to color the pLDDT based on the threshold confidence. Thanks

**Comment by Intron7** [comment]
Hey @milanborchert,
sorry for taking so long but the py3Dmol is very specific in what it wants and doesn't want. But I got the features running now. Expect a new version pip version tomorrow.

**Comment by Intron7** [comment]
> Nice tool indeed! I am using it and it works fine on MacOSX M1. Additional feature would be to color the pLDDT based on the threshold confidence. Thanks

@aspitaleri Glad you like the tool. Just to make sure I understood you correctly. You want a coloured line for the `plot_pLDDT` plot based on the value? Or did I get your idea wrong?

**Comment by aspitaleri** [comment]
Yes that could be work (i.e. plotly?) or like this in attach (got it from alphapickle)
![image](https://user-images.githubusercontent.com/41744541/213496117-5e88fda6-0619-4d1a-8784-f9ec4d5f42ad.png)

**Comment by Intron7** [comment]
alpha_viewer 0.1.5 just got released. Please check it out.

**Comment by milanborchert** [comment]
Thank you for implementing these changes. Great job.
