### ISSUE TITLE
Problem in viewing model in alpha-viewer

### ISSUE THREAD

**Issue by 456apu** [Intron7/alpha_viewer#3]
Hi,
Good afternoon. I am facing problem in generating Py3dmol image in alpha_viewer. I am using Jupyter-lab. Only Model confidence values are coming but not the model after typing in notebook:

viewer.show_confidence(style="cartoon")

Earlier it used to come. But this problem started recently. I also upgraded both alpha-viewer and jupyter-lab to their latest versions. As you can see in attached screen shot, both Matplotlib and jupyterlab_py3dmol extensions are enabled.
Please help.

Thanks,
Arpita

![Screenshot from 2023-03-04 16-17-43](https://user-images.githubusercontent.com/112276330/222895738-8b9253ae-7df3-4b17-a616-0d991b63c830.png)

**Comment by Intron7** [comment]
Hey Arpita,

This is not a bug with alpha_viewer. I also encounter it sometimes. You should try to update the py3dmol package `pip install py3Dmol -U` within your environment.

**Comment by 456apu** [comment]
Hi Severin,

That solved the problem. Thank you so much!
